### ISSUE TITLE
README for fabric-images is incorrect

### ISSUE THREAD

**Issue by kletkeman** [IBM-Blockchain/fabric-images#20]
The command to set up the environment is shown as

``` bash
. setup.sh
```

It should, of course, show a forward slash between the . and the setup.sh, but even that does not actually work, because the export commands for ARCH_TAG only export to *sub shells* and not to the parent shell, where the docker-compose command is executed next.

Instead, the README should show the following command:

```bash
source setup.sh
```

After that, the Dockerfile is correct and the parent shell knows ARCH_TAG.

**Comment by dhyey-ibm** [comment]
http://stackoverflow.com/questions/4732200/replacement-for-source-in-sh

`. setup.sh` and `source setup.sh` are the same commands.

**Comment by kletkeman** [comment]
Lol ... ok, you got me ... had nor seen that syntax, ever.

**Comment by kletkeman** [comment]
You learn something new every day ...
