### ISSUE TITLE
tag latest removed on dockerhub

### ISSUE THREAD

**Issue by vincentserpoul** [IBM-Blockchain/fabric-images#21]
this pull request fixes it.
https://github.com/IBM-Blockchain/fabric-images/pull/17

that said, I think it would be better to have a defined version instead of a random tag

**Comment by mrshah-at-ibm** [comment]
This is not the source image name, this is target image name. It is under `build` tag of compose file. It will use the Dockerfile inside the `baseimage` folder to build the image.

**Comment by vincentserpoul** [comment]
try to remove all your docker images and do a docker-compose up.
You will see it will try to pull the image with the tag latest.

**Comment by mrshah-at-ibm** [comment]
It should not. It should build using the `./baseimage` folder.
Ref: https://docs.docker.com/compose/compose-file/#/build

**Comment by vincentserpoul** [comment]
ok, I found the issue.
On mac, `. setenv.sh` doesn't work, and it was then not setting the ENV variable and stopping there, complaining about a missing manifest file.
`./setenv.sh` works... Dumb mistake :/.
I will create a small PR to prevent this from happening (it seems I wasn't the only one as there was another issue with the same symptoms)

**Comment by mrshah-at-ibm** [comment]
@vincentserpoul as you mentioned, the other issue has a solution comment which says `. setenv.sh` is same as `source setenv.sh`.

Ref: https://github.com/IBM-Blockchain/fabric-images/issues/21#issuecomment-273967109

Thus a PR is not necessary. Thank you.
