### ISSUE TITLE
ERROR: for vp Cannot create container for service up

### ISSUE THREAD

**Issue by qianlizimu** [IBM-Blockchain/fabric-images#27]
I used Docker Toolbox on Windows 7. I have pulled the fabric images and when I ran the ". setenv.sh" command and "docker-compose -f single-peer-ca.yaml up" command, I found this error message:
ERROR: for vp Cannot create container for service up: create \var\run\docker.sock: "\\var\\run\\docker.sock" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
<-[31mERROR<-[0m: Encountered errors while bringing up the project.

How to deal with this? Thanks!

**Comment by mrshah-at-ibm** [comment]
I recommend _not_ using Docker Toolbox.. we have seen issues with it. It will be good if you can try it on a Linux box

**Comment by qianlizimu** [comment]
@mrshah-at-ibm Thanks, but I'm not very familiar with Linux box. I cannot find where to download it on the Internet. How to install it? Can I use it in the Ubuntu(Linux) of VMware virtual machine or just in Windows? Thank you!

**Comment by mrshah-at-ibm** [comment]
yes you can use Ubuntu of VMware virtual machine. You can use Virtualbox and install a Linux VM on it. You will find a lot of tutorials online.

**Comment by qianlizimu** [comment]
OK, Thanks!
